### ISSUE TITLE
The OAuth 1.0a authentication seems deprecated

### ISSUE THREAD

**Issue by Yicong-Huang** [redouane59/twittered#177]
I am getting the following error when using API key and Access token to request for Twitter API V2 Full Archive Search. I don't find a way to supply Bearer token to the TwitterClient?

```https://api.twitter.com/2/tweets/search/all {"title":"Unsupported Authentication","detail":"Authentication with OAuth 1.0a User Context is forbidden. Please, make the request with OAuth 2.0 Bearer Token authentication.","type":"https://api.twitter.com/2/problems/unsupported-authentication"} - 403 ```

**Comment by redouane59** [comment]
Hi @Yicong-Huang , thanks for the issue. I think that's a regression related to a recent release. I'm going to fix it now.

**Comment by redouane59** [comment]
Issue will be fixed in the release v1.23 soon available today.

**Comment by Yicong-Huang** [comment]
Thanks for the quick fix! I confirm I have successfully integrated this full archive search API into our project. However, I still think it's better to go with the bearer token authentication method. I've used https://github.com/twitterdev/search-tweets-python/tree/v2 and they are using bearer token already. Wonder if possible to have a java version.

 I've seen #43 discussing this suggestion but got rejected, I would like to second that and know if the road map of this library has changed since then.

Thanks in advance!

**Comment by redouane59** [comment]
Hi @Yicong-Huang , i'm a little bit stuck with it. It's kind of difficult to allow this because `OAuth10aService` should be instantiate using an api key in `AbstractRequestHelper` class and it looks mandatory.

@PhantomYdn do you know if it's possible to instantiate it with a bearer token only ?
From your PR https://github.com/redouane59/twittered/pull/126 I think it was not  planned but if you have ideas don't hesitate :)
