### ISSUE TITLE
getUserTimeline returns more than configured

### ISSUE THREAD

**Issue by aless2003** [redouane59/twittered#232]
The getUserTimeline method returns more Tweets than set in the AdditionalParameters. It should have returned 38 Tweets, instead it returned 577. Is there anything I missed or is this a bug?

![image](https://user-images.githubusercontent.com/46018087/123921116-f7baed80-d986-11eb-818c-908fd2c779d7.png)

**Comment by redouane59** [comment]
Hi,
You need to set `recursiveCall` to `false` in `AdditionalParameters`, otherwise the method will call the endpoint X times with the `maxResults` you gave, but looping until `next_token` is null. 

I just developed this feature, maybe the documentation is bad, don't hesitate to suggest idead to improve it :)

**Comment by aless2003** [comment]
Ah alright thanks, yes if I do that it works, thanks!
