### ISSUE TITLE
Release build of library contains unnecessary runtime dependencies

### ISSUE THREAD

**Issue by jkolobok** [redouane59/twittered#79]
sonar-maven-plugin
jacoco-maven-plugin
com.google.api-client
logback-classic

2 http clients instead of 1 or even 0:
apache http client and okhttp

**Comment by redouane59** [comment]
Hi,
Thanks for your feedback.
If i'm not wrong: 
- com.google.api-client is used [here](https://github.com/redouane59/twittered/blob/develop/src/main/java/com/github/redouane59/twitter/signature/Oauth1SigningInterceptor.java#L44)
- logback is used all over the project through annotations `@Slf4j` and set up [here](https://github.com/redouane59/twittered/blob/develop/logback.xml)
- And sonar & jacoco plugin are used in order to build [this dashboard](https://sonarcloud.io/dashboard?id=redouane59_twittered)

Tell me if i'm not correct.

**Comment by jkolobok** [comment]
The general idea is that you want to minimize dependencies as much as possible. To avoid jar hell and other problems. 

Google api
yes, there are usages, but use are using only a couple of utility function bringing in the whole library  with all it's transitive dependencies. this is 100% wrong approach. 
Should either:  
1) Find the same functionality in another library(okhttp, apache httpclient or it should be available in jdk).
2) Copy only that logic to the project from google api lib

Logback
logback is logback. slf4j is slf4j. logback is one of the implementations if slf4j. So is you are using slf4j in the code (which is generated by lombok) need you to set slf4j as dependency for the library and not logback. if you want to see logs during tests you set logaback as test only dependency.  So if someone uses you library and different slf4j implementation he doesn't have extra runtime dependencies... or again jar-hell.

sonar & jacoco
These 2 libraries are not either runtime dependencies nor compile time. These are different things. jacoco is using only during test execution (thus you need to change scope to `test`). The same thing for sonar. if you want some kind od special build - create a maven profile to make a build for your needs. but make default build you deploy to public maven repo as clean(lesser dependencies) as possible. 

The same idea with okhttp and apache http client. both libraries have the same functionality. if you are using only utility function from one of libraries, copy them to your code of try to find in another library which you already have imported.

**Comment by redouane59** [comment]
Good points, thanks for feedback we'll watch it !

**Comment by hypr2771** [comment]
I think `logback-classic` pulls up SLF4J, and is required as an SLF4J implementation.
SLF4J is simply used to register logger API implementation, isn't it?
Hence, you'd need `logback-classic` when using `@Slf4j`, right?

**Comment by jkolobok** [comment]
logback-classic is not required neither during compile time (only slf4j is required), nor runtime (another implementation of slf4j can be used instead)

**Comment by hypr2771** [comment]
But you'll need one of them at runtime, right?
You mean that the application integrating the library will provide its own implementation?
What happens if they do not use an SLF4J implementation?

I think it's fine to provide a default SLF4J implementation (logback or log4j or even JUL) and eventually tell the integrator that they can `exclude` it in their POM to use their own implementation.
Don't you think it's poor design to rely on the runtime injection of a dependency from the JAR integrator?
